$script = <<-SCRIPT
#sudo wicked ifup eth1 eth2 eth3 eth4

cmdline="$(cat /proc/cmdline)"
datasource="$(host pit.nmn | awk '{print $NF}')"
cmdline="${cmdline} ds=nocloud-net;s=http://${datasource}:8888/"
echo "${cmdline}" > /tmp/cmdline
sudo chown -R root:root /root/.ssh
sudo mount -o bind /tmp/cmdline /proc/cmdline
sudo DI_LOG=stderr /usr/lib/cloud-init/ds-identify --force
sudo cloud-init clean --logs
sudo cloud-init init
sudo cloud-init modules -m init
sudo cloud-init modules -m config
sudo cloud-init modules -m final
SCRIPT


Vagrant.configure("2") do |config|

  # Download the latest box:
  # curl -f -o kubernetes-${ARCH}.box https://$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN@artifactory.algol60.net/artifactory/csm-images/stable/kubernetes/\\[RELEASE\\]/kubernetes-\\[RELEASE\\]-${ARCH}.box
  # curl -f -o storage-ceph-${ARCH}.box https://$ARTIFACTORY_USER:$ARTIFACTORY_TOKEN@artifactory.algol60.net/artifactory/csm-images/stable/storage-ceph/\\[RELEASE\\]/storage-ceph-\\[RELEASE\\]-${ARCH}.box
  config.vm.box = "kubernetes-x86_64.box"

  # Can't enable since nfs-client is not installed or installable.
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Necessary for cloud-init to work
  config.vm.synced_folder '/root/.ssh', '/root/.ssh', type: "rsync"

  # Requires VM-x to be enabled
  # config.vm.provider :libvirt do |libvirt|
  #  libvirt.pci :domain => '0x0000', :bus => '0x18', :slot => '0x00', :function => '0x0'
  # end

  # Run our init script for hacking the datasource into /proc/cmdline.
  config.vm.provision "shell", inline: $script

  config.vm.provider :libvirt do |libvirt|
    # Redbull:
    #
    # Threads:
    # ncn-m001: 112
    # ncn-m002: 80
    # ncn-m003: 80
    # ncn-s001: 80
    # ncn-s002: 112
    # ncn-s003: 112
    # ncn-s004: 16
    # ncn-w001: 80
    # ncn-w002: 80
    # ncn-w003: 80
    #
    # Memory
    # ncn-m001: MemTotal:       262376980 kB
    # ncn-m002: MemTotal:       262377268 kB
    # ncn-m003: MemTotal:       262376856 kB
    # ncn-s001: MemTotal:       263159944 kB
    # ncn-s002: MemTotal:       262369540 kB
    # ncn-s003: MemTotal:       262368788 kB
    # ncn-s004: MemTotal:       47711836 kB   <--- new node, equipped with less
    # ncn-w001: MemTotal:       262377624 kB
    # ncn-w002: MemTotal:       262376456 kB
    # ncn-w003: MemTotal:       262385804 kB
    libvirt.cpus = 48
    libvirt.memory = 65536
    libvirt.nested = true
  end

  config.vm.define :w001 do |w001|

    w001.vm.network :public_network,
                    :dev => "bond0.nmn0",
                    :mac => "52:54:00:01:43:67",
                    :libvirt__mtu => 9000
    # w001.vm.network :public_network,
    #                 :dev => "bond0.hmn0",
    #                 :mac => "52:54:00:01:43:67",
    #                 :libvirt__mtu => 9000
    # w001.vm.network :public_network,
    #                 :dev => "bond0.can0",
    #                 :mac => "52:54:00:01:43:67",
    #                 :libvirt__mtu => 9000
    # w001.vm.network :public_network,
    #                 :dev => "bond0.cmn0",
    #                 :mac => "52:54:00:01:43:67",
    #                 :libvirt__mtu => 9000
  end
  config.vm.define :w002 do |w002|

    w002.vm.network :public_network,
                    :dev => "bond0.nmn0",
                    :mac => "52:54:00:01:43:68",
                    :libvirt__mtu => 9000
    # w002.vm.network :public_network,
    #                 :dev => "bond0.hmn0",
    #                 :mac => "52:54:00:01:43:68",
    #                 :libvirt__mtu => 9000
    # w002.vm.network :public_network,
    #                 :dev => "bond0.can0",
    #                 :mac => "52:54:00:01:43:68",
    #                 :libvirt__mtu => 9000
    # w002.vm.network :public_network,
    #                 :dev => "bond0.cmn0",
    #                 :mac => "52:54:00:01:43:68",
    #                 :libvirt__mtu => 9000
  end
end
