= Hypervisor Proof of Concept
:toc:
:toclevels: 4
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

CAUTION: **For all intents and purposes this application is a pre-alpha used for a proof of concept.**

NOTE: Some of the proof of concept materials uses BASH, this BASH warrants a sense of caution.

== Resources

* The https://github.com/Cray-HPE/crucible[crucible] package
* The https://github.com/Cray-HPE/node-images/tree/hypervisor/boxes/hypervisor[hypervisor ISO]

== PoC Installation and Setup

=== Launching the LiveCD

1. Install `cruicble`, either from VCS using `pip` or from the downloaded RPM (see link:poc-app-download.adoc[RPM Download]).
+
* Without HTTP proxy
+
[source,bash]
----
python3 -m pip install git+https://github.com/Cray-HPE/crucible.git@main
crucible --version
----
* With HTTP proxy
+
[source,bash]
----
python3 -m pip --proxy=http://hpeproxy.its.hpecorp.net:443 install git+https://github.com/Cray-HPE/crucible.git@main
crucible --version
----
1. Fetch the ISO (see link:poc-iso-download.adoc[ISO Download]).
1. Write the ISO to a block device.
+
[source,bash]
----
crucible setup bootable /path/to/disk /path/to/hyperv 50000
----
1. Reboot to the device
* Optionally you may want to connect a serial console to the machine being rebooted before rebooting the device.
* Optionally use `ipmitool` to boot to BIOS, and then using the BIOS menu simply select the bootable device from the one-time boot menu.
+
[source,bash]
----
ipmitool chassis bootdev bios options=efiboot
ipmitool chassis power cycle
----
1. At the first login screen, set your password
+
NOTE: The initial password is blank.
1. (optionally) setup SSH now
+
[source,bash]
----
crucible setup ssh
----

=== Installing to Disk

1. Prepare the system by wiping the disks.
+
[source,bash]
----
crucible wipe -y
----
1. Install the hypervisor image to disk. This command will partition and format a few partitions; a bootloader, a root file system (overlayFS), and a large partition for VM guests.
+
[source,bash]
----
crucible install
----
1. Reboot to disk.
* Optionally remove your bootable media
* Optionally you may want to reconnect a serial console if you're not still connected from earlier.
* Optionally use `ipmitool` to boot to disk
+
[source,bash]
----
ipmitool chassis bootdev disk options=efiboot
ipmitool chassis power cycle
----
1. At the first login, set your password.
+
NOTE: The initial password is blank.
1. Setup SSH
* Optionally setup SSH now
+
[source,bash]
----
crucible setup ssh
----

Once connectivity is established, further setup and launching can be done on the hypervisor.

=== Configure VMs

Run the Hypervisor Ansible playbook to setup the machine for VMs.

[source,bash]
source /opt/cray/ansible/bin/activate
ansible-playbook /srv/cray/metal-provision/site.yml --tags hypervisor

=== Launch VMs

TODO
